/* Automatically generated by D:\csapp\game_framework\src\parse_array.py, DO NOT edit by hand. */
%include carrays.i
%include cdata.i

/* Opt */
%array_class(Opt, Opt_Array)
%cdata(Opt)

/* ROLE_INFO */
%array_class(ROLE_INFO, ROLE_INFO_Array)
%cdata(ROLE_INFO)

/* ACC_INFO */
%array_class(ACC_INFO, ACC_INFO_Array)
%cdata(ACC_INFO)

/* D:\csapp\game_framework\src\game_framework_array.i Ends here. */
